### ISSUE TITLE
Jupyter notebooks available?

### ISSUE THREAD

**Issue by dougnukem** [dnanexus/OpenBio#9]
I see a list of Jupyter notebooks listed here: 
- https://github.com/dnanexus/OpenBio/blob/master/UKB_notebooks/notebook_description.tsv

But this repository doesn't seem to contain the actual notebooks (are they located in a different repo?)

e.g. pheno_geno_linker_R.ipynb

**Comment by djemec** [comment]
Hi.  We are in the process of reorganizing this repo and cleaning up previous files.  For further help on a specific topic please reach out to ukbiobank-support@dnanexus.com
